apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: rsshub

resources: []
  # - resources/external-secrets.yaml

helmCharts:
  - name: app-template
    namespace: rsshub
    releaseName: rsshub
    repo: https://bjw-s-labs.github.io/helm-charts/
    valuesFile: rsshub.yaml
    version: 4.6.2
  - name: app-template
    namespace: rsshub
    releaseName: redis
    repo: https://bjw-s-labs.github.io/helm-charts/
    valuesFile: redis.yaml
    version: 4.6.2
  - name: app-template
    namespace: rsshub
    releaseName: real-browser
    repo: https://bjw-s-labs.github.io/helm-charts/
    valuesFile: real-browser.yaml
    version: 4.6.2
