---
esphome:
  name: "${name}"
  name_add_mac_suffix: true

  project:
    name: "${project_name}"
    version: "${project_version}"
  on_boot:
    priority: 240
    then:
      - wait_until:
          condition:
            wifi.connected:
          timeout: 10s
  on_shutdown:
    then:
      - switch.turn_off: spower

dashboard_import:
  package_import_url: github://bruvv/LILYGO-T-Higrow-Esphome/LILYGO-T-Higrow-ESP32.yaml@main

esp32:
  board: lolin_d32

improv_serial:

logger:
  level: "${loglevel}"

button:
  - platform: restart
    name: "Restart - ${name}"

i2c:
  sda: 25
  scl: 26
  scan: true
  id: bus_a
  setup_priority: -200

switch:
  # Power Switch
  - platform: gpio
    name: "${name} Sensor Power switch"
    pin:
      number: 4
      mode: INPUT_PULLUP
    id: spower
    restore_mode: ALWAYS_ON
    internal: true
    setup_priority: 1000
  - platform: gpio
    pin: GPIO19
    name: "Water Pump"
    id: water

sensor:
  - platform: wifi_signal
    name: "${friendly_name} - WiFi Signal"
    update_interval: ${update_interval}
    icon: mdi:wifi-strength-1
  # DHT
  - platform: dht
    pin: 16
    model: dht11
    temperature:
      name: "${friendly_name} DHT Temperature"
      unit_of_measurement: "°C"
      icon: "mdi:thermometer"
      device_class: "temperature"
      state_class: "measurement"
      accuracy_decimals: 1
      filters: # uncomment after calibration
        - offset: -3.1 # offset in °C for the measured temperature
    humidity:
      name: "${friendly_name} DHT Humidity"
      unit_of_measurement: "%"
      icon: "mdi:cloud-percent"
      device_class: "humidity"
      state_class: "measurement"
      accuracy_decimals: 1
      filters: # uncomment after calibration
        - offset: 11 # offset in % for the measured humidity
    setup_priority: -100
    update_interval: ${update_interval}
  # Soil humidity %
  - platform: adc
    pin: GPIO32
    name: "${friendly_name} Soil Moisture"
    icon: "mdi:watering-can"
    update_interval: ${update_interval}
    attenuation: 11db
    accuracy_decimals: 2 # comment for calibration
    unit_of_measurement: "%" # comment for calibration
    id: moisture
    device_class: moisture
    state_class: measurement
    # unit_of_measurement: "V" # uncomment for calibration
    filters: # comment when calibrating
      - calibrate_linear: # comment when calibrating
          # Map 0.0 (from sensor) to 0.0 (true value)
          - ${moisture_min} -> 0.0 # comment when calibrating
          - ${moisture_max} -> 100.0 # comment when calibrating

  # Fertilizer sensor
  - platform: adc
    pin: GPIO34
    name: "${friendly_name} Soil Conductivity"
    icon: "mdi:flower"
    update_interval: ${update_interval}
    accuracy_decimals: 2 # comment for calibration
    unit_of_measurement: "µS/cm" # comment when calibrating
    # device_class: '' # for now home assistant does not support this class
    state_class: "measurement"
    # unit_of_measurement: "V" # uncomment for raw data
    filters: # comment when calibrating
      - calibrate_linear: # comment when calibrating
          # Map 0.0 (from sensor) to 0.0 (true value)
          - ${conductivity_min} -> 0.0 # comment when calibrating
          - ${conductivity_max} -> 100.0 # comment when calibrating

  # Lux sensor
  - platform: bh1750
    i2c_id: bus_a
    name: "${friendly_name} BH1750 Illuminance"
    address: 0x23
    unit_of_measurement: "lx"
    icon: "mdi:white-balance-sunny"
    device_class: "illuminance"
    state_class: "measurement"
    setup_priority: -300
    update_interval: ${update_interval}
    # convert to illuminance
    filters:
      - lambda: |-
          return x * 200.0;

text_sensor:
  # Installed version
  - platform: template
    name: "${friendly_name} - Installed version"
    icon: "mdi:label-outline"
    entity_category: diagnostic
    lambda: |-
      return {"${project_version}"};
    update_interval: 6h
  - platform: version
    hide_timestamp: true
    name: "${friendly_name} - ESPHome Version"
# climate:
#   - platform: bang_bang
#     visual:
#       min_temperature: 0
#       max_temperature: 100
#       temperature_step: 1

#     name: ${friendly_name} Regler
#     # TODO: check
#     sensor: moisture
#     default_target_temperature_low: 20
#     default_target_temperature_high: 70

#     heat_action:
#       - switch.turn_on: water

#     idle_action:
#       - switch.turn_off: water
# packages:
#   # Battery only works for 12 hours with deepsleep!
#   deepsleep: !include https://github.com/bruvv/LILYGO-T-Higrow-Esphome/blob/4eba66ad27f2bea9e632ff7eeb703e06d6f102c6/common/deepsleep.yaml
#   battery: !include https://github.com/bruvv/LILYGO-T-Higrow-Esphome/blob/4eba66ad27f2bea9e632ff7eeb703e06d6f102c6/common/battery.yaml
