apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - resources/pod-monitor.yaml
  - resources/prometheus-rules-alerts.yaml

helmGlobals:
  chartHome: helm-charts
helmCharts:
  - name: postgres-operator
    repo: https://opensource.zalando.com/postgres-operator/charts/postgres-operator/
    version: 1.15.1
    includeCRDs: true
    releaseName: postgres-operator
    namespace: postgres-operator
    valuesFile: values.yaml

configMapGenerator:
  - name: postgres-dashboards
    files:
      - dashboards/general.json
      - dashboards/overview.json

generatorOptions:
  annotations:
    argocd.argoproj.io/compare-options: IgnoreExtraneous
    argocd.argoproj.io/sync-options: Replace=true
    k8s-sidecar-target-directory: /tmp/dashboards/postgres
  labels:
    grafana_dashboard: "1"
