---

- name: update-ca-certificates  # noqa: name[casing]
  command: update-ca-certificates

- name: restart sshd  # noqa: name[casing]
  service:
    name: ssh
    state: restarted

- name: update grub  # noqa: name[casing]
  command: update-grub

- name: restart cpufrequtils  # noqa: name[casing]
  service:
    name: cpufrequtils
    state: restarted

- name: restart systemd-logind  # noqa: name[casing]
  systemd:
    name: systemd-logind
    daemon_reload: true
    state: restarted

- name: restart systemd-journald  # noqa: name[casing]
  systemd:
    name: systemd-journald
    daemon_reload: true
    state: restarted

- name: apply network interface  # noqa: name[casing]
  command: netplan apply

- name: unattended-upgrades | restart systemd service  # noqa: name[casing]
  ansible.builtin.service:
    name: unattended-upgrades.service
    daemon_reload: true
    enabled: true
    state: restarted

- name: unattended-upgrades | ignore armbian changes  # noqa: name[casing]
  command: dpkg-divert --no-rename --add /etc/apt/apt.conf.d/02-armbian-periodic
  when:
    - ansible_architecture == "aarch64"

- name: apt autoremove  # noqa: name[casing]
  apt:
    autoremove: true

- name: restart server  # noqa: name[casing]
  vars:
    ansible_user: "{{ prepare_username }}"
  reboot:

- name: restart apparmor  # noqa: name[casing]
  service:
    name: apparmor
    state: restarted
