apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: flaresolverr

helmCharts:
  - name: app-template
    namespace: flaresolverr
    releaseName: flaresolverr
    repo: https://bjw-s.github.io/helm-charts/
    valuesFile: values.yaml
    version: 3.6.0
