apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ci-runners
resources:
  - resources/configmap.yaml
  - resources/cronjob.yaml
  - resources/external-secret-keda.yaml
  - resources/external-secret-runner.yaml
  # Ephemeral workers need caches for forgejo runner and docker, so I will keep a simpler config
  # - resources/scale-job.yaml
  - resources/pvc-runner-cache.yaml
  - resources/pvc-runner-docker.yaml
  - resources/statefulset.yaml
  - resources/trigger-authentication.yaml
