apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ci-runners
resources:
  - resources/configmap.yaml
  - resources/external-secret-keda.yaml
  - resources/external-secret-runner.yaml
  - resources/scale-job.yaml
  - resources/trigger-authentication.yaml
