substitutions:
  name: "mini-switch-4"
  friendly_name: "Mini Switch 4"
  project_name: "athom.mini-switch-4"
  project_version: "1.1"
  light_restore_mode: RESTORE_DEFAULT_OFF

esphome:
  name: "${name}"
  name_add_mac_suffix: true
  project:
    name: "${project_name}"
    version: "${project_version}"

esp8266:
  board: esp8285
  restore_from_flash: true

api:
  encryption:
    key: !secret home_assistant_api_key

ota:
  safe_mode: true
  password: !secret ota_password

logger:
  baud_rate: 0

mdns:
  disabled: false

web_server:
  port: 80

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  domain: !secret domain_devices

  ap:
    ssid: "Rack-Controller Fallback Hotspot"
    password: !secret wifi_fallback_ap_password

captive_portal:

dashboard_import:
  package_import_url: github://athom-tech/athom-configs/athom-mini-switch.yaml

button:
  - platform: factory_reset
    name: Restart with Factory Default Settings
    id: Reset

output:
  - platform: gpio
    id: relay_output
    pin: GPIO13

light:
  - platform: status_led
    id: led
    name: "${friendly_name} Blue LED"
    disabled_by_default: true
    pin:
      number: GPIO4
      inverted: true

  - platform: binary
    id: mini_relay
    output: relay_output
    name: "${friendly_name} Light"
    restore_mode: ${light_restore_mode}

sensor:
  - platform: uptime
    name: "${friendly_name} Uptime"
    disabled_by_default: true

  - platform: wifi_signal
    name: "${friendly_name} WiFi Signal"
    update_interval: 60s

binary_sensor:
  # Wired switch
  - platform: gpio
    id: the_switch
    name: "${friendly_name} Power Switch"
    disabled_by_default: true
    pin:
      number: GPIO14
      mode: INPUT_PULLUP
    on_state:
      - light.toggle: mini_relay
      - light.toggle: led
    on_multi_click:
      - timing:
          - ON for at most 0.5s
          - OFF for at most 0.5s
          - ON for at most 0.5s
          - OFF for at most 0.5s
          - ON for at most 0.5s
          - OFF for at most 0.5s
          - ON for at most 0.5s
          - OFF for at most 0.5s
        then:
          - button.press: Reset

  # Button on mini switch
  - platform: gpio
    pin:
      number: GPIO3
      mode: INPUT_PULLUP
      inverted: true
    name: "${friendly_name} Power Button"
    disabled_by_default: true
    on_multi_click:
      - timing:
          - ON for at most 1s
          - OFF for at least 0.2s
        then:
          - light.toggle: mini_relay
          - light.toggle: led
      - timing:
          - ON for at least 4s
        then:
          - button.press: Reset

  - platform: status
    name: "${friendly_name} Status"
text_sensor:
  - platform: wifi_info
    ip_address:
      name: "${friendly_name} IP Address"
      disabled_by_default: true

time:
  - platform: sntp
    id: sntp_time
    servers:
      - pfsense.grigri
