apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
# namespace cannot be set here because the helm chart deploys rolebinding in kube-system
helmCharts:
  - includeCRDs: true
    name: keda
    namespace: keda
    releaseName: keda
    repo: https://kedacore.github.io/charts
    valuesFile: values.yaml
    version: 2.19.0

patches:
  - patch: |-
      - op: add
        path: "/metadata/annotations/argocd.argoproj.io~1sync-options"
        value: "Replace=true"
    target:
      group: apiextensions.k8s.io
      kind: CustomResourceDefinition
