# renovate: datasource=github-releases depName=k3s-io/k3s versioning=regex:^v(?<major>\d+)(\.(?<minor>\d+))?(\.(?<patch>\d+))\+k3s?((?<build>\d+))$
k3s_version: v1.30.6+k3s1
k3s_config_file: /etc/rancher/k3s/config.yaml
k3s_token_file: /etc/rancher/node/password
k3s_service_file: /etc/systemd/system/k3s.service
k3s_kubelet_extra_args: []
k3s_server_config:
  disable:
    - local-storage
    - servicelb
    - traefik
  disable-cloud-controller: true
  secrets-encryption: true
