apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - server.yaml
  - agent.yaml

commonAnnotations:
  # TODO: https://github.com/rancher/system-upgrade-controller/issues/172
  argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true

patches:
  - patch: |-
      - op: add
        path: /spec/version
        # renovate: datasource=github-releases depName=k3s-io/k3s versioning=regex:^v(?<major>\d+)(\.(?<minor>\d+))?(\.(?<patch>\d+))\+k3s?((?<build>\d+))$
        value: v1.30.7+k3s1
    target:
      group: upgrade.cattle.io
      version: v1
      kind: Plan
      name: .*
