---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: esphome-secrets
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault
  target:
    name: esphome-secrets
    template:
      engineVersion: v2
      data:
        secrets.yaml: |-
          wifi_ssid: {{`"{{ .wifi_ssid }}"`}}
          wifi_password: {{`"{{ .wifi_password }}"`}}
          wifi_fallback_password: {{`"{{ .wifi_fallback_ap_password }}"`}}
          ota_password: {{`"{{ .ota_password }}"`}}

          home_assistant_api_key: {{`"{{ .home_assistant_api_key }}"`}}
          # ¯\_(ツ)_/¯ just copy/paste
          domain_devices: .iot.grigri
  data:
    - secretKey: ota_password
      remoteRef:
        key: /esphome/ota
        property: password
    - secretKey: wifi_ssid
      remoteRef:
        key: /esphome/wifi
        property: ssid
    - secretKey: wifi_password
      remoteRef:
        key: /esphome/wifi
        property: password
    - secretKey: wifi_fallback_ap_password
      remoteRef:
        key: /esphome/wifi
        property: fallback_ap_password
    - secretKey: home_assistant_api_key
      remoteRef:
        key: /esphome/home-assistant
        property: api_key
    # in template:
    # mqtt_host: mosquitto.internal.grigri.cloud
    # mqtt_user: {{`"{{ .mosquitoto_username }}"`}}
    # mqtt_pwd: {{`"{{ .mosquitoto_password }}"`}}
    # - secretKey: mosquitoto_username
    #   remoteRef:
    #     key: /mosquitto/user
    #     property: username
    # - secretKey: mosquitoto_password
    #   remoteRef:
    #     key: /mosquitto/password
    #     property: password
