---
# apply with `ANSIBLE_EXTRA_ARGS='-t zfs-exporter' make cluster` in metal dir
# renovate: datasource=github-releases depName=pdf/zfs_exporter
zfs_exporter_version: 2.3.11
# deadline: Maximum duration that a collection should run before returning cached data.
#     Should be set to a value shorter than your scrape timeout duration. The current collection
#     run will continue and update the cache when complete (default: 8s)
zfs_exporter_arguments: --collector.dataset-snapshot --deadline=8s
